[package]
name = "CliUdpChat"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
serde_json = "1.0.117"
serde = { version = "1.0.203", features = ["derive"] }
